server:
  port: 8094
spring:
  application:
    name: bl-springcloud-zookeeper-dubbo-server

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_study?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver



  #追踪
  sleuth:
    web:
    client:
      enabled: true

    sampler:
    probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://127.0.0.1:9411/ # 指定了 Zipkin 服务器的地址
    rabbitmq:
      queue: zipkin
      base-url: http://127.0.0.1:9411/ # 指定了 Zipkin 服务器的地址
      addresses: 127.0.0.1:5672
      username: root
      password: root

  #rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root


  boot:
    admin:
      client:
        url: http://localhost:8091
        username: ${lionet.security.user}
        password: ${lionet.security.password}

lionet:
  security:
    user: root
    password: root



management:
  endpoints:
    web:
      exposure:
        include: '*' # 代表开启所有健康检查; management.health.*.enabled=false
  health:
    # 禁用 redis 健康检查
    redis:
      enabled: false

# 注意 此配置不能放入 bootstrap.yml,具体原因暂时未排查, 后续需更新
dubbo:
  application:
    name: lionetService
    protocol:
      name: dubbo
      port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
  scan: com.bravelionet.service



#MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.xp.**.domain #类型扫描不持支*需要结合方法
# 配置mapper的扫描，找到所有的mapper.xml映射文件 这里没有加* 这是错误一
  mapper-locations: classpath:com.bravelionet.mapper/*.xml
# 加载全局的配置文件
configLocation: classpath:mybatis/mybatis-config.xml



