server:
  port: 8093
spring:
  application:
    name: spring-cloud-config-clinet
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud_config?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  profiles:
    active: master
  # 配置语言包,  ConfigServer 无用; MessageSourceAutoConfiguration Springboot 默认配置了语言包,在请求头中区分地区
  messages:
    basename: messages





  #rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root


management:
  endpoints:
    web:
      exposure:
        include: bus-refresh # // 刷新端点


 # auditevents	显示当前应用程序的审计事件信息	Yes
 # beans	显示应用Spring Beans的完整列表	Yes
 # caches	显示可用缓存信息	Yes
 # conditions	显示自动装配类的状态及及应用信息	Yes
 # configprops	显示所有 @ConfigurationProperties 列表	Yes
 # env	显示 ConfigurableEnvironment 中的属性	Yes
 # flyway	显示 Flyway 数据库迁移信息	Yes
 # health	显示应用的健康信息（未认证只显示status，认证显示全部信息详情）	No
 # info	显示任意的应用信息（在资源文件写info.xxx即可）	No
 # liquibase	展示Liquibase 数据库迁移	Yes
 # metrics	展示当前应用的 metrics 信息	Yes
 # mappings	显示所有 @RequestMapping 路径集列表	Yes
 # scheduledtasks	显示应用程序中的计划任务	Yes
 # sessions	允许从Spring会话支持的会话存储中检索和删除用户会话。	Yes
 # shutdown	允许应用以优雅的方式关闭（默认情况下不启用）	Yes
 # threaddump	执行一个线程dump	Yes
 # httptrace	显示HTTP跟踪信息（默认显示最后100个HTTP请求 - 响应交换）	Yes


